# Q1

# **Assignment NLP**

**Group No.:** 18

**Group Members:**

1. VARINDER SINGH  - 2021fc04070@wilp.bits-pilani.ac.in

2. BANDARU RAJA SEKHAR  - 2021fc04074@wilp.bits-pilani.ac.in

3. MIKHIL. P.A.  - 2021fc04326@wilp.bits-pilani.ac.in

# Q1. 
Consider the text string

text = """Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multi-planet species by building a self-sustaining city on Mars. In 2008, SpaceX’s Falcon 1 became the first privately developed liquid-fuel launch vehicle to orbit the Earth. 🥶😇👌 """

Apply the following text processing methods using python NLTK library
1.	Word tokenization
2.	Sentence tokenization
3.	Tweet tokenization
4.	MWETokenizer
5.	RegexpTokenizer
6.	TextBlob Word Tokenize
7.	List noun_phrases
8.	Determine sentiment.polarity

In [82]:
import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
from nltk import RegexpParser
from nltk import Tree
import pandas as pd

nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('vader_lexicon')
nltk.download('brown')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /home/datalore/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /home/datalore/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/datalore/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to /home/datalore/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/datalore/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package brown to /home/datalore/nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

In [83]:
text_data = """Founded in 2002, SpaceX’s mission is to enable humans \
to become a spacefaring civilization and a multi-planet species by building a \
self-sustaining city on Mars. In 2008, SpaceX’s Falcon 1 became the first privately \
developed liquid-fuel launch vehicle to orbit the Earth. 🥶😇👌 """

## 1. Word Tokenisation

In [84]:
from nltk.tokenize import word_tokenize
word_tokenize(text_data)

['Founded',
 'in',
 '2002',
 ',',
 'SpaceX',
 '’',
 's',
 'mission',
 'is',
 'to',
 'enable',
 'humans',
 'to',
 'become',
 'a',
 'spacefaring',
 'civilization',
 'and',
 'a',
 'multi-planet',
 'species',
 'by',
 'building',
 'a',
 'self-sustaining',
 'city',
 'on',
 'Mars',
 '.',
 'In',
 '2008',
 ',',
 'SpaceX',
 '’',
 's',
 'Falcon',
 '1',
 'became',
 'the',
 'first',
 'privately',
 'developed',
 'liquid-fuel',
 'launch',
 'vehicle',
 'to',
 'orbit',
 'the',
 'Earth',
 '.',
 '🥶😇👌']

## 2. Sentence Tokenisation

In [85]:
from nltk.tokenize import sent_tokenize
sent_tokenize(text_data)

['Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multi-planet species by building a self-sustaining city on Mars.',
 'In 2008, SpaceX’s Falcon 1 became the first privately developed liquid-fuel launch vehicle to orbit the Earth.',
 '🥶😇👌']

## 3. Tweet tokenization

In [86]:
from nltk.tokenize import TweetTokenizer

tk = TweetTokenizer()
tk.tokenize(text_data)

['Founded',
 'in',
 '2002',
 ',',
 'SpaceX',
 '’',
 's',
 'mission',
 'is',
 'to',
 'enable',
 'humans',
 'to',
 'become',
 'a',
 'spacefaring',
 'civilization',
 'and',
 'a',
 'multi-planet',
 'species',
 'by',
 'building',
 'a',
 'self-sustaining',
 'city',
 'on',
 'Mars',
 '.',
 'In',
 '2008',
 ',',
 'SpaceX',
 '’',
 's',
 'Falcon',
 '1',
 'became',
 'the',
 'first',
 'privately',
 'developed',
 'liquid-fuel',
 'launch',
 'vehicle',
 'to',
 'orbit',
 'the',
 'Earth',
 '.',
 '🥶',
 '😇',
 '👌']

## 4. MWETokenizer

In [87]:

from nltk.tokenize import MWETokenizer

tk = MWETokenizer([('Founded', 'in', '2002,'),
                   ('SpaceX’s', 'mission'),
                   ('enable', 'humans'),
                   ('spacefaring', 'civilization'),
                   ('multi-planet', 'species'),
                   ('self-sustaining', 'city'),
                   ('SpaceX’s', 'Falcon'),
                   ('privately', 'developed', 'liquid-fuel', 'launch', 'vehicle'),
                   ('orbit', 'the', 'Earth.')
                ]
                  , separator="+")
token = tk.tokenize(text_data.split())

for i in token:
    print(i)

Founded+in+2002,
SpaceX’s+mission
is
to
enable+humans
to
become
a
spacefaring+civilization
and
a
multi-planet+species
by
building
a
self-sustaining+city
on
Mars.
In
2008,
SpaceX’s+Falcon
1
became
the
first
privately+developed+liquid-fuel+launch+vehicle
to
orbit+the+Earth.
🥶😇👌


## 5. RegexpTokenizer

In [88]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('[\d\.]+')
tokenizer.tokenize(text_data)

['2002', '.', '2008', '1', '.']

## 6. TextBlob Word Tokenize

In [89]:
from textblob import TextBlob
	
blob_object = TextBlob(text_data)

print(" Word Tokenize :\n", blob_object.words)
print("\n Sentence Tokenize :\n", blob_object.sentences)

 Word Tokenize :
 ['Founded', 'in', '2002', 'SpaceX', '’', 's', 'mission', 'is', 'to', 'enable', 'humans', 'to', 'become', 'a', 'spacefaring', 'civilization', 'and', 'a', 'multi-planet', 'species', 'by', 'building', 'a', 'self-sustaining', 'city', 'on', 'Mars', 'In', '2008', 'SpaceX', '’', 's', 'Falcon', '1', 'became', 'the', 'first', 'privately', 'developed', 'liquid-fuel', 'launch', 'vehicle', 'to', 'orbit', 'the', 'Earth', '🥶😇👌']

 Sentence Tokenize :
 [Sentence("Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multi-planet species by building a self-sustaining city on Mars."), Sentence("In 2008, SpaceX’s Falcon 1 became the first privately developed liquid-fuel launch vehicle to orbit the Earth."), Sentence("🥶😇👌")]


## 7. List noun_phrases

In [90]:
nouns = blob_object.noun_phrases
nouns = set(nouns)

print("Nouns in the text_data:\n-------------------------")
for i in nouns:
    if not(str(i).__contains__("’ s")):
        print(str(i).capitalize())

Nouns in the text_data:
-------------------------
Earth
Falcon
Multi-planet species
Founded
Liquid-fuel launch vehicle
Enable humans
Spacex
Mars


## 8. Determine sentiment.polarity

In [91]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

for i in sent_tokenize(text_data):
    sia = SentimentIntensityAnalyzer()
    print(i)
    print(sia.polarity_scores(i)) 
    print('\n')

Founded in 2002, SpaceX’s mission is to enable humans to become a spacefaring civilization and a multi-planet species by building a self-sustaining city on Mars.
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}


In 2008, SpaceX’s Falcon 1 became the first privately developed liquid-fuel launch vehicle to orbit the Earth.
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}


🥶😇👌
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}




# Q2

# Q2.
Discuss bag of words model and apply it on following documents.

doc1 = 'Game of Thrones is an amazing tv series!' <br>
doc2 = 'Game of Thrones is the best tv series!' <br>
doc3 = 'Game of Thrones is so great' <br>

The bag-of-words model is a way of representing text data when modeling text with machine learning algorithms.

The bag-of-words model is simple to understand and implement and has seen great success in problems such as language modeling and document classification. Whenever we apply any algorithm in NLP, it works on numbers. We cannot directly feed our text into that algorithm. Hence, Bag of Words model is used to preprocess the text by converting it into a bag of words, which keeps a count of the total occurrences of most frequently used words.

This model can be visualized using a table, which contains the count of words corresponding to the word itself.

In [92]:
import pandas as pd
import numpy as np
import re

In [93]:
doc1 = 'Game of Thrones is an amazing tv series!'
doc2 = 'Game of Thrones is the best tv series!'
doc3 = 'Game of Thrones is so great'

l_doc1 = re.sub(r"[^a-zA-Z0-9]", " ", doc1.lower()).split()
l_doc2 = re.sub(r"[^a-zA-Z0-9]", " ", doc2.lower()).split()
l_doc3 = re.sub(r"[^a-zA-Z0-9]", " ", doc3.lower()).split()

wordset12 = np.union1d(l_doc1,l_doc2)
wordset =  np.union1d(wordset12,l_doc3)
print(wordset)

['amazing' 'an' 'best' 'game' 'great' 'is' 'of' 'series' 'so' 'the'
 'thrones' 'tv']


In [94]:
def calculate_bow(word_set,l_doc):
  tf_diz = dict.fromkeys(word_set,0)
  for word in l_doc:
      tf_diz[word]=l_doc.count(word)
  return tf_diz

In [95]:
bow1 = calculate_bow(wordset,l_doc1)
bow2 = calculate_bow(wordset,l_doc2)
bow3 = calculate_bow(wordset,l_doc3)
df_bow = pd.DataFrame([bow1,bow2,bow3])
df_bow.head()

amazing 
 an 
 best 
 game 
 great 
 is 
 of 
 series 
 so 
 the 
 thrones 
 tv 
 
 
 
 
 0 
 1 
 1 
 0 
 1 
 0 
 1 
 1 
 1 
 0 
 0 
 1 
 1 
 
 
 1 
 0 
 0 
 1 
 1 
 0 
 1 
 1 
 1 
 0 
 1 
 1 
 1 
 
 
 2 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 0 
 1 
 0

# Q3

# Q3. 
Discuss TF-IDF model and find the TF-ID score of words for the following dataset

<br>

dataset = [ <br>
"I enjoy reading about Machine Learning and Data Science",<br>
"Machine Learning is the field of study that gives computers the capability to learn without being explicitly programmed.",<br>
"Data science is the field of study that combines domain expertise, programming skills, and knowledge of mathematics and statistics to extract meaningful insights from data.",<br>
 "I would enjoy a walk in the park",<br>
 "I was reading in the library"<br>
]

TF-IDF stands for Term Frequency Inverse Document Frequency of records. It can be defined as the calculation of how relevant a word in a series or corpus is to a text. The meaning increases proportionally to the number of times in the text a word appears but is compensated by the word frequency in the corpus (data-set).

TF-IDF for a word in a document is calculated by multiplying two different metrics:

- The term frequency of a word in a document. There are several ways of calculating this frequency, with the simplest being a raw count of instances a word appears in a document. Then, there are ways to adjust the frequency, by length of a document, or by the raw frequency of the most frequent word in a document. The weight of a term that occurs in a document is simply proportional to the term frequency.

    tf(t,d) = count of t in d / number of words in d


- The inverse document frequency of the word across a set of documents. This means, how common or rare a word is in the entire document set. The closer it is to 0, the more common a word is. This metric can be calculated by taking the total number of documents, dividing it by the number of documents that contain a word, and calculating the logarithm.

- So, if the word is very common and appears in many documents, this number will approach 0. Otherwise, it will approach 1.

- Multiplying these two numbers results in the TF-IDF score of a word in a document. The higher the score, the more relevant that word is in that particular document.

In [96]:
dataset = [
"I enjoy reading about Machine Learning and Data Science",
"Machine Learning is the field of study that gives computers the capability to learn without being explicitly programmed.",
"Data science is the field of study that combines domain expertise, programming skills, and knowledge of mathematics and statistics to extract meaningful insights from data.",
"I would enjoy a walk in the park",
"I was reading in the library"
]

In [97]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
result = tfidf.fit_transform(dataset)
result

<5x41 sparse matrix of type '<class 'numpy.float64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [98]:
print(tfidf.get_feature_names_out())

['about' 'and' 'being' 'capability' 'combines' 'computers' 'data' 'domain'
 'enjoy' 'expertise' 'explicitly' 'extract' 'field' 'from' 'gives' 'in'
 'insights' 'is' 'knowledge' 'learn' 'learning' 'library' 'machine'
 'mathematics' 'meaningful' 'of' 'park' 'programmed' 'programming'
 'reading' 'science' 'skills' 'statistics' 'study' 'that' 'the' 'to'
 'walk' 'was' 'without' 'would']


In [99]:
print('\nIDF Values:\n---------------------------\n---------------------------\n')

for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)


IDF Values:
---------------------------
---------------------------

about : 2.09861228866811
and : 1.6931471805599454
being : 2.09861228866811
capability : 2.09861228866811
combines : 2.09861228866811
computers : 2.09861228866811
data : 1.6931471805599454
domain : 2.09861228866811
enjoy : 1.6931471805599454
expertise : 2.09861228866811
explicitly : 2.09861228866811
extract : 2.09861228866811
field : 1.6931471805599454
from : 2.09861228866811
gives : 2.09861228866811
in : 1.6931471805599454
insights : 2.09861228866811
is : 1.6931471805599454
knowledge : 2.09861228866811
learn : 2.09861228866811
learning : 1.6931471805599454
library : 2.09861228866811
machine : 1.6931471805599454
mathematics : 2.09861228866811
meaningful : 2.09861228866811
of : 1.6931471805599454
park : 2.09861228866811
programmed : 2.09861228866811
programming : 2.09861228866811
reading : 1.6931471805599454
science : 1.6931471805599454
skills : 2.09861228866811
statistics : 2.09861228866811
study : 1.6931471805599454


In [100]:
# get indexing
print('\nWord Indexes:\n---------------------------\n---------------------------\n')
print(tfidf.vocabulary_)


Word Indexes:
---------------------------
---------------------------

{'enjoy': 8, 'reading': 29, 'about': 0, 'machine': 22, 'learning': 20, 'and': 1, 'data': 6, 'science': 30, 'is': 17, 'the': 35, 'field': 12, 'of': 25, 'study': 33, 'that': 34, 'gives': 14, 'computers': 5, 'capability': 3, 'to': 36, 'learn': 19, 'without': 39, 'being': 2, 'explicitly': 10, 'programmed': 27, 'combines': 4, 'domain': 7, 'expertise': 9, 'programming': 28, 'skills': 31, 'knowledge': 18, 'mathematics': 23, 'statistics': 32, 'extract': 11, 'meaningful': 24, 'insights': 16, 'from': 13, 'would': 40, 'walk': 37, 'in': 15, 'park': 26, 'was': 38, 'library': 21}


In [101]:
# display tf-idf values
print('\nTF-IDF value:\n---------------------------\n---------------------------\n')
print(result)


TF-IDF value:
---------------------------
---------------------------

  (0, 30)	0.3422671810690251
  (0, 6)	0.3422671810690251
  (0, 1)	0.3422671810690251
  (0, 20)	0.3422671810690251
  (0, 22)	0.3422671810690251
  (0, 0)	0.4242313488433432
  (0, 29)	0.3422671810690251
  (0, 8)	0.3422671810690251
  (1, 27)	0.2628220441905301
  (1, 10)	0.2628220441905301
  (1, 2)	0.2628220441905301
  (1, 39)	0.2628220441905301
  (1, 19)	0.2628220441905301
  (1, 36)	0.2120431703907612
  (1, 3)	0.2628220441905301
  (1, 5)	0.2628220441905301
  (1, 14)	0.2628220441905301
  (1, 34)	0.2120431703907612
  (1, 33)	0.2120431703907612
  (1, 25)	0.2120431703907612
  (1, 12)	0.2120431703907612
  (1, 35)	0.2961387104469203
  (1, 17)	0.2120431703907612
  (1, 20)	0.2120431703907612
  (1, 22)	0.2120431703907612
  :	:
  (2, 28)	0.20398018031255918
  (2, 9)	0.20398018031255918
  (2, 7)	0.20398018031255918
  (2, 4)	0.20398018031255918
  (2, 36)	0.16456992511251706
  (2, 34)	0.16456992511251706
  (2, 33)	0.164569925112517

In [102]:
# in matrix form
print('\nTF-IDF values in matrix form:\n---------------------------\n---------------------------\n')
print(result.toarray())


TF-IDF values in matrix form:
---------------------------
---------------------------

[[0.42423135 0.34226718 0.         0.         0.         0.
  0.34226718 0.         0.34226718 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.34226718 0.         0.34226718 0.
  0.         0.         0.         0.         0.         0.34226718
  0.34226718 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.26282204 0.26282204 0.         0.26282204
  0.         0.         0.         0.         0.26282204 0.
  0.21204317 0.         0.26282204 0.         0.         0.21204317
  0.         0.26282204 0.21204317 0.         0.21204317 0.
  0.         0.21204317 0.         0.26282204 0.         0.
  0.         0.         0.         0.21204317 0.21204317 0.29613871
  0.21204317 0.         0.         0.26282204 0.        ]
 [0.         0.32913985 0.         0.       

# Q4

# Q4. 
Apply the following data preprocessing techniques on iris data set. Iris dataset is freely available.

<br>

1)Decimal Scaling<br>
2)Min-Max Normalization<br>
3)z-Score Normalization (zero-mean Normalization)<br>

In [103]:
from sklearn import datasets

# import iris data
iris = datasets.load_iris()
X = iris.data[:, :]
y = iris.target

In [104]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### 1) Decimal Scaling

In [105]:
X_new = X.copy()

column = len(X_new[0,:])

#getting max out of the column
arr = []
for i in range(column):
    arr.append(X_new[:, int(i)].max())

#getting the significant digit of the max number
for i in range(column):
    arr[i] = len(str(int(arr[i])))

#getting the decimal number to multiple to df
for i in range(column):
    num = int(arr[i])
    for j in range(num):
        arr[i] = arr[i] * 10

#making changes to the df
for i in range(column):
    X_new[:, int(i)] = X_new[:, int(i)] / arr[i]

print(X_new)

[[0.51 0.35 0.14 0.02]
 [0.49 0.3  0.14 0.02]
 [0.47 0.32 0.13 0.02]
 [0.46 0.31 0.15 0.02]
 [0.5  0.36 0.14 0.02]
 [0.54 0.39 0.17 0.04]
 [0.46 0.34 0.14 0.03]
 [0.5  0.34 0.15 0.02]
 [0.44 0.29 0.14 0.02]
 [0.49 0.31 0.15 0.01]
 [0.54 0.37 0.15 0.02]
 [0.48 0.34 0.16 0.02]
 [0.48 0.3  0.14 0.01]
 [0.43 0.3  0.11 0.01]
 [0.58 0.4  0.12 0.02]
 [0.57 0.44 0.15 0.04]
 [0.54 0.39 0.13 0.04]
 [0.51 0.35 0.14 0.03]
 [0.57 0.38 0.17 0.03]
 [0.51 0.38 0.15 0.03]
 [0.54 0.34 0.17 0.02]
 [0.51 0.37 0.15 0.04]
 [0.46 0.36 0.1  0.02]
 [0.51 0.33 0.17 0.05]
 [0.48 0.34 0.19 0.02]
 [0.5  0.3  0.16 0.02]
 [0.5  0.34 0.16 0.04]
 [0.52 0.35 0.15 0.02]
 [0.52 0.34 0.14 0.02]
 [0.47 0.32 0.16 0.02]
 [0.48 0.31 0.16 0.02]
 [0.54 0.34 0.15 0.04]
 [0.52 0.41 0.15 0.01]
 [0.55 0.42 0.14 0.02]
 [0.49 0.31 0.15 0.02]
 [0.5  0.32 0.12 0.02]
 [0.55 0.35 0.13 0.02]
 [0.49 0.36 0.14 0.01]
 [0.44 0.3  0.13 0.02]
 [0.51 0.34 0.15 0.02]
 [0.5  0.35 0.13 0.03]
 [0.45 0.23 0.13 0.03]
 [0.44 0.32 0.13 0.02]
 [0.5  0.35

### 2) Min-Max Normalization

In [106]:
from sklearn.preprocessing import MinMaxScaler

# define min max scaler
scaler = MinMaxScaler()
# transform data
MinMaxScaled = scaler.fit_transform(X)
print(MinMaxScaled)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

### 3) z-Score Normalization

In [107]:
from sklearn.preprocessing import StandardScaler

# define standard scaler
scaler = StandardScaler()
# transform data
StandardScaled = scaler.fit_transform(X)
print(StandardScaled)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e